import { Component } from 'react';
import { NavLink as Link } from 'react-router-dom';

export default class ManualSidebar extends Component {
  render() {
    return (
      <ul className="main-menu nav nav-stacked">
        <li>
          <Link exact to="/docs/reference/guide/">
            Guide to The Microservices
          </Link>
        </li>
        <li>
          <Link exact to="/docs/reference/platform/">
            Taskcluster Platform
          </Link>
          <ul>
            <li>
              <Link exact to="/docs/reference/platform/taskcluster-auth/">
                taskcluster-auth
              </Link>
              <div className="inline-navs">
                (
                <Link
                  exact
                  to="/docs/reference/platform/taskcluster-auth/references/api">
                  api
                </Link>
                |
                <Link
                  exact
                  to="/docs/reference/platform/taskcluster-auth/references/events">
                  events
                </Link>
                )
              </div>
              <ul>
                <li>
                  <Link
                    exact
                    to="/docs/reference/platform/taskcluster-auth/docs/clients">
                    clients
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/platform/taskcluster-auth/docs/scopes">
                    Scopes and Satisfaction
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/platform/taskcluster-auth/docs/roles">
                    Roles and Role Expansion
                  </Link>
                </li>
              </ul>
            </li>
            <li>
              <Link exact to="/docs/reference/platform/taskcluster-queue/">
                taskcluster-queue
              </Link>
              <div className="inline-navs">
                (
                <Link
                  exact
                  to="/docs/reference/platform/taskcluster-queue/references/api">
                  api
                </Link>
                |
                <Link
                  exact
                  to="/docs/reference/platform/taskcluster-queue/references/events">
                  events
                </Link>
                )
              </div>
              <ul>
                <li>
                  <Link
                    exact
                    to="/docs/reference/platform/taskcluster-queue/docs/worker-hierarchy">
                    Worker Hierarchy
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/platform/taskcluster-queue/docs/actions">
                    Actions
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/platform/taskcluster-queue/docs/superseding">
                    Superseding
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/platform/taskcluster-queue/docs/task-life-cycle">
                    Task Life-Cycle
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/platform/taskcluster-queue/docs/worker-interaction">
                    Queue-Worker Interaction
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/platform/taskcluster-queue/docs/task-schema">
                    Task Schema
                  </Link>
                </li>
              </ul>
            </li>
          </ul>
        </li>
        <li>
          <Link exact to="/docs/reference/core/">
            Core Services
          </Link>
          <ul>
            <li>
              <Link exact to="/docs/reference/core/purge-cache/">
                purge-cache
              </Link>
              <div className="inline-navs">
                (
                <Link
                  exact
                  to="/docs/reference/core/purge-cache/references/api">
                  api
                </Link>
                |
                <Link
                  exact
                  to="/docs/reference/core/purge-cache/references/events">
                  events
                </Link>
                )
              </div>
            </li>
            <li>
              <Link exact to="/docs/reference/core/taskcluster-hooks/">
                taskcluster-hooks
              </Link>
              <div className="inline-navs">
                (
                <Link
                  exact
                  to="/docs/reference/core/taskcluster-hooks/references/api">
                  api
                </Link>
                |
                <Link
                  exact
                  to="/docs/reference/core/taskcluster-hooks/references/events">
                  events
                </Link>
                )
              </div>
              <ul>
                <li>
                  <Link
                    exact
                    to="/docs/reference/core/taskcluster-hooks/docs/firing-hooks">
                    Firing Hooks
                  </Link>
                </li>
              </ul>
            </li>
            <li>
              <Link exact to="/docs/reference/core/taskcluster-index/">
                taskcluster-index
              </Link>
              <div className="inline-navs">
                (
                <Link
                  exact
                  to="/docs/reference/core/taskcluster-index/references/api">
                  api
                </Link>
                )
              </div>
            </li>
            <li>
              <Link exact to="/docs/reference/core/taskcluster-notify/">
                taskcluster-notify
              </Link>
              <div className="inline-navs">
                (
                <Link
                  exact
                  to="/docs/reference/core/taskcluster-notify/references/api">
                  api
                </Link>
                |
                <Link
                  exact
                  to="/docs/reference/core/taskcluster-notify/references/events">
                  events
                </Link>
                )
              </div>
              <ul>
                <li>
                  <Link
                    exact
                    to="/docs/reference/core/taskcluster-notify/docs/usage">
                    Enable Notifications
                  </Link>
                </li>
              </ul>
            </li>
            <li>
              <Link exact to="/docs/reference/core/taskcluster-index/">
                taskcluster-secrets
              </Link>
              <div className="inline-navs">
                (
                <Link
                  exact
                  to="/docs/reference/core/taskcluster-secrets/references/api">
                  api
                </Link>
                )
              </div>
            </li>
            <li>
              <Link exact to="/docs/reference/core/taskcluster-events/">
                taskcluster-events
              </Link>
            </li>
          </ul>
        </li>
        <li>
          <Link exact to="/docs/reference/integrations/">
            Integrations
          </Link>
          <ul>
            <li>
              <Link exact to="/docs/reference/integrations/aws-provisioner/">
                aws-provisioner
              </Link>
              <div className="inline-navs">
                (
                <Link
                  exact
                  to="/docs/reference/integrations/aws-provisioner/references/api">
                  api
                </Link>
                |
                <Link
                  exact
                  to="/docs/reference/integrations/aws-provisioner/references/events">
                  events
                </Link>
                )
              </div>
            </li>
            <li>
              <Link exact to="/docs/reference/integrations/cloud-mirror/">
                cloud-mirror
              </Link>
            </li>
            <li>
              <Link exact to="/docs/reference/integrations/taskcluster-github/">
                taskcluster-github
              </Link>
              <div className="inline-navs">
                (
                <Link
                  exact
                  to="/docs/reference/integrations/taskcluster-github/references/api">
                  api
                </Link>
                |
                <Link
                  exact
                  to="/docs/reference/integrations/taskcluster-github/references/events">
                  events
                </Link>
                )
              </div>
              <ul>
                <li>
                  <Link
                    exact
                    to="/docs/reference/integrations/taskcluster-github/docs/intro">
                    Using Taskcluster for Github Projects
                  </Link>
                  <Link
                    exact
                    to="/docs/reference/integrations/taskcluster-github/docs/taskcluster-yml-v0">
                    .taskcluster.yml
                  </Link>
                </li>
              </ul>
            </li>
            <li>
              <Link exact to="/docs/reference/integrations/taskcluster-login/">
                taskcluster-login
              </Link>
              <div className="inline-navs">
                (
                <Link
                  exact
                  to="/docs/reference/integrations/taskcluster-login/references/api">
                  api
                </Link>
                )
              </div>
              <ul>
                <li>
                  <Link
                    exact
                    to="/docs/reference/integrations/taskcluster-login/docs/getting-user-creds">
                    Getting User Credentials
                  </Link>
                </li>
              </ul>
            </li>
            <li>
              <Link
                exact
                to="/docs/reference/integrations/mozilla-taskcluster/">
                mozilla-taskcluster
              </Link>
              <ul>
                <li>
                  <Link
                    exact
                    to="/docs/reference/integrations/mozilla-taskcluster/docs/developing">
                    Developing
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/integrations/mozilla-taskcluster/docs/taskcluster-yml">
                    .taskcluster.yml
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/integrations/mozilla-taskcluster/docs/pushlog">
                    Pushlog Monitoring
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/integrations/mozilla-taskcluster/docs/how-to">
                    How-Tos
                  </Link>
                </li>
              </ul>
            </li>
            <li>
              <Link exact to="/docs/reference/integrations/taskcluster-pulse/">
                taskcluster-pulse
              </Link>
              <div className="inline-navs">
                (
                <Link
                  exact
                  to="/docs/reference/integrations/taskcluster-pulse/references/api">
                  api
                </Link>
                )
              </div>
            </li>
            <li>
              <Link
                exact
                to="/docs/reference/integrations/taskcluster-treeherder/">
                taskcluster-treeherder
              </Link>
              <div className="inline-navs">
                (
                <Link
                  exact
                  to="/docs/reference/integrations/taskcluster-treeherder/references/events">
                  events
                </Link>
                )
              </div>
              <ul>
                <li>
                  <Link
                    exact
                    to="/docs/reference/integrations/taskcluster-treeherder/docs/task-treeherder-config">
                    Task Schema
                  </Link>
                </li>
              </ul>
            </li>
            <li>
              <Link
                exact
                to="/docs/reference/integrations/taskcluster-host-secrets/">
                taskcluster-host-secrets
              </Link>
              <ul>
                <li>
                  <Link
                    exact
                    to="/docs/reference/integrations/taskcluster-host-secrets/docs/deployment">
                    Deploying the Service
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/integrations/taskcluster-host-secrets/docs/getting-credentials">
                    Getting Credentials
                  </Link>
                </li>
              </ul>
            </li>
            <li>
              <Link exact to="/docs/reference/integrations/taskcluster-tools/">
                taskcluster-tools
              </Link>
              <ul>
                <li>
                  <Link
                    exact
                    to="/docs/reference/integrations/taskcluster-host-secrets/docs/creating-clients">
                    Creating Clients
                  </Link>
                </li>
              </ul>
            </li>
          </ul>
        </li>
        <li>
          <Link exact to="/docs/reference/operations/">
            Operations
          </Link>
          <ul>
            <li>
              <Link exact to="/docs/reference/operations/statsum/">
                statsum
              </Link>
            </li>
            <li>
              <Link
                exact
                to="/docs/reference/operations/taskcluster-diagnostics/">
                taskcluster-diagnostics
              </Link>
            </li>
            <li>
              <Link
                exact
                to="/docs/reference/operations/taskcluster-stats-collector/">
                taskcluster-stats-collector
              </Link>
            </li>
          </ul>
        </li>
        <li>
          <Link exact to="/docs/reference/workers/">
            Workers
          </Link>
          <ul>
            <li>
              <Link exact to="/docs/reference/workers/docker-worker/">
                docker-worker
              </Link>
              <ul>
                <li>
                  <Link
                    exact
                    to="/docs/reference/workers/docker-worker/docs/payload">
                    Payload Format
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/workers/docker-worker/docs/scopes">
                    Scopes
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/workers/docker-worker/docs/environment">
                    Environment Variables
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/workers/docker-worker/docs/caches">
                    Caches
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/workers/docker-worker/docs/features">
                    Features
                  </Link>
                </li>
              </ul>
            </li>
            <li>
              <Link exact to="/docs/reference/workers/generic-worker/">
                generic-worker
              </Link>
              <ul>
                <li>
                  <Link
                    exact
                    to="/docs/reference/workers/generic-worker/docs/payload">
                    Payload Format
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/workers/generic-worker/docs/features">
                    Features
                  </Link>
                </li>
              </ul>
            </li>
            <li>
              <Link exact to="/docs/reference/workers/taskcluster-worker/">
                taskcluster-worker
              </Link>
              <ul>
                <li>
                  <Link
                    exact
                    to="/docs/reference/workers/taskcluster-worker/docs/configuration">
                    Configuration
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/workers/taskcluster-worker/docs/architecture">
                    Architecture
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/workers/taskcluster-worker/docs/engine-flow">
                    Engine Life-Cycle
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/workers/taskcluster-worker/docs/plugin-flow">
                    Plugin Life-Cycle
                  </Link>
                </li>
              </ul>
            </li>
          </ul>
        </li>
        <li>
          <Link exact to="/docs/reference/libraries/">
            Libraries
          </Link>
          <ul>
            <li>
              <Link exact to="/docs/reference/libraries/azure-blob-storage/">
                azure-blob-storage
              </Link>
            </li>
            <li>
              <Link exact to="/docs/reference/libraries/azure-entities/">
                azure-entities
              </Link>
            </li>
            <li>
              <Link
                exact
                to="/docs/reference/libraries/docker-exec-websocket-server/">
                docker-exec-websocket-server
              </Link>
            </li>
            <li>
              <Link exact to="/docs/reference/libraries/fast-azure-storage/">
                fast-azure-storage
              </Link>
            </li>
            <li>
              <Link exact to="/docs/reference/libraries/go-schematypes/">
                go-schematypes
              </Link>
            </li>
            <li>
              <Link exact to="/docs/reference/libraries/json-e/">
                json-e
              </Link>
            </li>
            <li>
              <Link exact to="/docs/reference/libraries/pulse-publisher/">
                pulse-publisher
              </Link>
            </li>
            <li>
              <Link exact to="/docs/reference/libraries/taskcluster-cli/">
                taskcluster-cli
              </Link>
            </li>
            <li>
              <Link exact to="/docs/reference/libraries/taskcluster-client/">
                taskcluster-client
              </Link>
            </li>
            <li>
              <Link exact to="/docs/reference/libraries/taskcluster-client-go/">
                taskcluster-client-go
              </Link>
            </li>
            <li>
              <Link
                exact
                to="/docs/reference/libraries/taskcluster-client-java/">
                taskcluster-client-java
              </Link>
            </li>
            <li>
              <Link
                exact
                to="/docs/reference/workers/libraries/taskcluster-client-web/">
                taskcluster-client-web
              </Link>
              <ul>
                <li>
                  <Link
                    exact
                    to="/docs/reference/libraries/taskcluster-client-web/docs/auth">
                    auth
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/libraries/taskcluster-client-web/docs/authevents">
                    authevents
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/libraries/taskcluster-client-web/docs/awsprovisioner">
                    awsprovisioner
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/libraries/taskcluster-client-web/docs/awsprovisionerevents">
                    awsprovisionerevents
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/libraries/taskcluster-client-web/docs/ec2-manager">
                    ec2-manager
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/libraries/taskcluster-client-web/docs/github">
                    github
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/libraries/taskcluster-client-web/docs/githubevents">
                    githubevents
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/libraries/taskcluster-client-web/docs/hooks">
                    hooks
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/libraries/taskcluster-client-web/docs/login">
                    login
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/libraries/taskcluster-client-web/docs/notify">
                    notify
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/libraries/taskcluster-client-web/docs/purgecache">
                    purgecache
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/libraries/taskcluster-client-web/docs/purgecacheevents">
                    purgecacheevents
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/libraries/taskcluster-client-web/docs/queue">
                    queue
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/libraries/taskcluster-client-web/docs/queueevents">
                    queueevents
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/libraries/taskcluster-client-web/docs/secrets">
                    secrets
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/libraries/taskcluster-client-web/docs/treeherderevents">
                    treeherderevents
                  </Link>
                </li>
              </ul>
            </li>
            <li>
              <Link exact to="/docs/reference/libraries/taskcluster-client.py/">
                taskcluster-client.py
              </Link>
            </li>
            <li>
              <Link exact to="/docs/reference/libraries/taskcluster-lib-api/">
                taskcluster-lib-api
              </Link>
            </li>
            <li>
              <Link exact to="/docs/reference/libraries/taskcluster-lib-app/">
                taskcluster-lib-app
              </Link>
            </li>
            <li>
              <Link exact to="/docs/reference/libraries/taskcluster-lib-docs/">
                taskcluster-lib-docs
              </Link>
              <ul>
                <li>
                  <Link
                    exact
                    to="/docs/reference/libraries/taskcluster-lib-docs/docs/documenting-non-services">
                    Documenting Non-Services
                  </Link>
                </li>
                <li>
                  <Link
                    exact
                    to="/docs/reference/libraries/taskcluster-lib-docs/docs/format">
                    Documentation Tarball Format
                  </Link>
                </li>
              </ul>
            </li>
            <li>
              <Link
                exact
                to="/docs/reference/libraries/taskcluster-lib-iterate/">
                taskcluster-lib-iterate
              </Link>
            </li>
            <li>
              <Link
                exact
                to="/docs/reference/libraries/taskcluster-lib-loader/">
                taskcluster-lib-loader
              </Link>
            </li>
            <li>
              <Link exact to="/docs/reference/libraries/taskcluster-lib-log/">
                taskcluster-lib-log
              </Link>
            </li>
            <li>
              <Link
                exact
                to="/docs/reference/libraries/taskcluster-lib-scopes/">
                taskcluster-lib-scopes
              </Link>
            </li>
            <li>
              <Link
                exact
                to="/docs/reference/libraries/taskcluster-lib-testing/">
                taskcluster-lib-testing
              </Link>
            </li>
            <li>
              <Link
                exact
                to="/docs/reference/libraries/taskcluster-lib-validate/">
                taskcluster-lib-validate
              </Link>
            </li>
            <li>
              <Link
                exact
                to="/docs/reference/libraries/taskcluster-lib-monitor/">
                taskcluster-lib-monitor
              </Link>
            </li>
            <li>
              <Link exact to="/docs/reference/libraries/typed-env-config/">
                typed-env-config
              </Link>
            </li>
            <li>
              <Link exact to="/docs/reference/libraries/ws-shell/">
                ws-shell
              </Link>
            </li>
          </ul>
        </li>
      </ul>
    );
  }
}
