export const FETCH_TASKS = 'FETCH_TASKS';
export const FETCH_TASK = 'FETCH_TASK';
export const FETCH_STATUS = 'FETCH_STATUS';
export const ACTIVE_TASK_STATUS = 'ACTIVE_TASK_STATUS';
export const UPDATE_STATUS = 'UPDATE_STATUS';
export const FETCH_ARTIFACTS = 'FETCH_ARTIFACTS';
export const CREATE_TASK = 'CREATE_TASK';
export const TASK_ACTIONS_ERROR = 'TASK_ACTIONS_ERROR';
export const TASK_ACTIONS_SUCCESS = 'TASK_ACTIONS_SUCCESS';
export const TASK_ACTIONS_IN_PROGRESS = 'TASK_ACTIONS_IN_PROGRESS';
export const SET_DASHBOARD_BANNER = 'SET_DASHBOARD_BANNER';
export const TASKS_NOT_AVAILABLE = 'TASKS_NOT_AVAILABLE';
export const REMOVE_TASKS = 'REMOVE_TASKS';
export const TASKS_RETRIEVED_FULLY = 'TASKS_RETRIEVED_FULLY';

