export const FETCH_TASKS = 'FETCH_TASKS';
export const FETCH_TASK = 'FETCH_TASK';
export const FETCH_STATUS = 'FETCH_STATUS';
export const ACTIVE_TASK_STATUS = 'ACTIVE_TASK_STATUS';
export const UPDATE_STATUS = 'UPDATE_STATUS';
export const FETCH_ARTIFACTS = 'FETCH_ARTIFACTS';
