import React from 'react';
import { render } from 'react-dom';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'font-awesome/css/font-awesome.min.css';
import App from './App';

const root = document.getElementById('root');
const load = () => render(<App />, root);
const getRevision = async () => (await fetch('/COMMITHASH')).text();

load();

(async () => {
  // Check the /COMMITHASH file generated by the `revision`
  // plugin in .neutrinorc.js every 5 minutes
  const rev = await getRevision();

  setInterval(async () => {
    const updatedRev = await getRevision();

    if (updatedRev !== rev) {
      location.reload(true);
    }
  }, 5 * 1000 * 60);
})();
